[window]
padding = { x = 2, y = 2 }
option_as_alt = 'Both'
startup_mode = "Maximized"

[cursor]
style = { shape = "Block", blinking = "On" }

[hints]
enabled = []

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

# Windows shell configuration - use cmd.exe as default
[terminal.shell]
program = "pwsh.exe"
